### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by jrborbars** [sasaporta/flask-security-admin-example#1]
I'm experiencing an issue with your stack, testing it in a brand new environment [1]. The only change is in line that connect to PGSQL (that I changed to connect to sqlite3). The db was created sucessfully. But this [2] message still broken the system, and I search for something, but can't solve this. Maybe an update/upgrade issue?

[1] - Environment
Archlinux x86_64 (kernel 4.1.6)
blinker==1.4
Flask==0.10.1
Flask-Admin==1.3.0
Flask-Login==0.3.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security==1.7.4
Flask-SQLAlchemy==2.0
Flask-WTF==0.12
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
passlib==1.6.5
SQLAlchemy==1.0.8
Werkzeug==0.10.4
WTForms==2.0.2

[2] - The message.
Traceback (most recent call last):
  File "/myapp/flask/lib/python3.5/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/myapp/flask/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/myapp/flask/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/myapp/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/myapp/flask/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/myapp/flask/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/myapp/flask/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/myapp/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/myapp/flask/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/myapp/flask/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/myapp/flask/lib/python3.5/site-packages/flask_security/decorators.py", line 203, in wrapper
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable

Best regards,

**Comment by sasaporta** [comment]
There was a recent change to Flask-Security (version 1.7.4) that introduced
a problem because it's not compatible with the latest version of
Flask-Login. You can read more about that here:
http://stackoverflow.com/questions/26313325/typeerror-bool-object-is-not-callable-in-flask

For a possible fix, you can change requirements.txt to make sure an earlier
version of Flask-Login is installed. Rather than Flask-Login==0.3.1,
try Flask-Login==0.2.11.
(If a later version of Flask-Login is already installed, you'd need to
remove it first.)

If this helps for you, would you let me know, and I'll update the code?

Regards,

Steve

**Comment by jrborbars** [comment]
Thank you for your quickly response. ;-)
Unfortunately, not works. Another thing still hang the system.
Traceback (most recent call last):
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask_login.py", line 283, in _load_user
    deleted = self._session_protection()
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask_login.py", line 298, in _session_protection
    ident = _create_identifier()
  File "/srv/http/prof/fornec/flask/lib/python3.5/site-packages/flask_login.py", line 669, in _create_identifier
    base = unicode(base, 'utf-8', errors='replace')
NameError: name 'unicode' is not defined

I have no time (now) to search a solution, so I post here the new error message. Maybe its trivial, maybe not.

Best regards and thank you.

**Comment by sasaporta** [comment]
The application is working fine for me on Windows, using either Python 2.7
or 3.3. I Googled your error message and found some references to "Unicode"
changing to "str" in Python 3.3. This might have introduced an
incompatibility in one of the Python packages.

You might try Python 2.7 until you have a chance to research it further.

In case it helps, here's a list (from pip freeze) of all packages I have
installed for 2.7 and 3.3.

PYTHON 2.7 PACKAGES
Flask==0.10.1
Flask-Admin==1.0.8
Flask-Login==0.2.10
Flask-Mail==0.9.0
Flask-Principal==0.4.0
Flask-SQLAlchemy==2.0
Flask-Security==1.7.1
Flask-WTF==0.9.5
Jinja2==2.7.3
MarkupSafe==0.23
SQLAlchemy==0.9.8
WTForms==1.0.5
Werkzeug==0.10.1
blinker==1.3
boto==2.38.0
certifi==2015.04.28
colorama==0.3.1
ecdsa==0.11
itsdangerous==0.24
numpy==1.9.1
paramiko==1.14.0
passlib==1.6.2
pil==1.1.7
psycopg2==2.5.2
pycrypto==2.6
pycurl==7.19.3
requests==2.2.1
selenium==2.44.0
termcolor==1.1.0
urllib3==1.10.4

PYTHON 3.3 PACKAGES
Flask==0.10.1
Flask-Admin==1.0.7
Flask-Login==0.2.10
Flask-Mail==0.9.0
Flask-Principal==0.4.0
Flask-SQLAlchemy==1.0
Flask-Security==1.7.1
Flask-WTF==0.9.5
Jinja2==2.7.2
MarkupSafe==0.18
SQLAlchemy==0.9.4
WTForms==1.0.5
Werkzeug==0.9.4
blinker==1.3
boto==2.27.0
image==1.2
itsdangerous==0.23
openpyxl==1.6.2
passlib==1.6.2
pillow==2.3.0
psycopg2==2.5.1
selenium==2.41.0
virtualenv==1.11.2

-Steve

**Comment by jrborbars** [comment]
You are right. Python2 and flask-login < 0.3 do the job.
